### ISSUE TITLE
Feature: turn off class-transformer for an individual route

### ISSUE THREAD

**Issue by charsleysa** [pleerock/routing-controllers#193]
Hi all,

One pain point I have is when using class-transformer I can't seem to return a buffer because the class-transformer keeps trying to process it.

I use class-transformer for almost all routes but I need some individual routes returning stuff that express can handle (such as buffers) but shouldn't be processed by class-transformer.

The current workaround is to get the response object using the `@Res()` decorator and calling the `send()` method with the buffer as the parameter.

I dislike this because it doesn't follow the execution flow of routing-controllers (e.g. none of the interceptors are called before the result is returned to the client).

Cheers!

**Comment by 19majkel94** [comment]
I wonder how we should do this:

1. Detect if the action is json typed (`@JsonController` or `@JsonResponse`), so the returned object is data object and we should transform it using `class-transform` and return using `res.json()`. Otherwise don't transform and use `res.send(result)`.
1. Detect type of the response - if it's `Buffer` don't transform, if `Stream` pipe to response, otherwise transform and send.
1. Introduce decorator like `@RawResponse()` to bypass the class-transformer transforming - might be helpfull with big and weird objects from ODM/ORM.

@pleerock @NoNameProvided any thoughts? 😉

**Comment by NoNameProvided** [comment]
As #226 has a broader conversation about the topic I will close this as a duplicate. 
Please subscribe to #226 to be notified when the required changes land. Thanks.
