### ISSUE TITLE
Check if headers were sent in controller

### ISSUE THREAD

**Issue by patrickhousley** [pleerock/routing-controllers#249]
When attempting to use the response object in my controller to set up a succeed fast scenario, routing-controllers are still trying to write headers and send data when my controller finishes running. Example:

```typescript

@JsonController('/auth')
export class ForgotPasswordController implements ForgotPasswordControllerAttributes {

  @Post('/forgotPassword')
  public async forgotPassword(
    @Res() response: express.Response,
    @Body({ validate: { skipMissingProperties: true } })
    body: ForgotPasswordRequest
  ) {
    // Response fast
    response.status(204).send();

    // Additional processing, might even use a return statement to end execution fast
  }
}
```

This results in error `Unhandled Promise rejection: Error: Can't set headers after they are sent.`.

**Comment by 19majkel94** [comment]
It happens because returning `undefined` means `404 Not Found` for routing-controllers. So it tries to send error response. But it should wait with it until you return from an action - I think your handler is async and callback based, so try return promise instead. I cannot reproduce with simple fast sync return:
```ts
@Get("/raw/:id")
rawExpress(@Req() req: Request, @Res() res: Response) {
    res.json({ id: req.params.id })
}
```
Does the error `Unhandled Promise rejection: Error: Can't set headers after they are sent.` comes from your controller action or from routing-controllers code after your response 204? What is the error code of response in Postman?

**Comment by patrickhousley** [comment]
Well how embarrassing. It would seem I had an error in my code that was throwing an exception. After tracking that down, it is working. I would say that solves this bug.
