### ISSUE TITLE
Suggest to support socket.io

### ISSUE THREAD

**Issue by xujif** [pleerock/routing-controllers#292]

**Comment by 19majkel94** [comment]
https://github.com/pleerock/socket-controllers

**Comment by pleerock** [comment]
@19majkel94 maybe we'll merge socket-controllers into routing-controllers, what do you think?

**Comment by 19majkel94** [comment]
I'm not sure. Not everyone want to use websockets in his rest api, so we can force people to download more code and deps that they don't use.

What's wrong with separate package? Do we have class interoperability, so you can have one method which accept POST request and notify all connected websockets about changes?

**Comment by pleerock** [comment]
> Not everyone want to use websockets in his rest api

same for people who are not using uploading. Not everyone needs uploading on their site as well. However I personally think websockets must be integrated much more in modern sites then right now. I think all modern sites must use websockets, its a really great thing that improves user experience a lot.

> so we can force people to download more code and deps that they don't use.

thats a small downside, but maybe its okay? Or maybe we can make it same as with other modules like express, koa etc - make it dynamic?

> What's wrong with separate package? Do we have class interoperability, so we can have one method which accept POST request and notify all connected websockets about changes?

I thought since we are kinda moving to a framework maybe it will be good idea to merge this functionality as well. Also problem in maintenance and popularity. Its harder to maintain this thing as its separate (tbh its not maintained at all right now) plus its not popular because people dont know about it and maybe dont want to use it. With it integrated into routing-controllers in will solve both problems - will be maintained much better and people will pay attention on it even those who didn't wanted to use it before at all

**Comment by 19majkel94** [comment]
> thats a small downside, but maybe its okay?

Since express/koa typings was too big to download on install...

> Or maybe we can make it same as with other modules like express, koa etc - make it dynamic?

It's a great solution - if someone use the socket.io decorator, it will check if the socket-controller with socket.io is loaded, if not it will try to require, if not it will print error. `@UploadedFile` works that way, right?

> I thought since we are kinda moving to a framework maybe it will be good idea to merge this functionality as well. Also problem in maintenance and popularity. Its harder to maintain this thing as its separate (tbh its not maintained at all right now) plus its not popular because people dont know about it and maybe dont want to use it. With it integrated into routing-controllers in will solve both problems - will be maintained much better and people will pay attention on it even those who didn't wanted to use it before at all

So you would like to make routing-controller not a routing framework but whole backend framework?
To merge this we definitely need new name, because websocket have no routing, only messages 😉 But I agree that it's not exposed and people don't know about it, so it might be good move. However I don't know how big merge you would like to do, rather than reexport socket's feature in main `routing-controllers` export.
