### ISSUE TITLE
Dashes in get param value is not accepted

### ISSUE THREAD

**Issue by thijsvanbuuren** [pleerock/routing-controllers#51]
`
@Get('/:uuid/stuff')
public getSomething(@Param('uuid') uuid) {
}
 `
When i use the above, and sent a /1234-234234-24324234/stuff (as example)
I get a 'Error' @  HttpError.js:18:22

**Comment by thijsvanbuuren** [comment]
If i do it through `@Req() request` and `request.params.uuid`  it does work as a workaround

**Comment by pleerock** [comment]
hmm thats strange, I'll take a look on this one

**Comment by dhaw92** [comment]
Hi, I wanted to fix the bug but it turned about that it is a JSON.parse syntax error (caused by the dash) since the string will be treated as an object if you don't specify the type. 
So if you specify that uuid is a string you wont get the error @thijsvanbuuren

**Comment by Luke265** [comment]
if "reflect-metadata" cannot identify param type, it's "design:paramtypes" function will return "object" and "routing-controllers" will try to parse that param as json, there comes the error. In order to make `@Get('/:uuid/stuff') public getSomething(@Param('uuid') uuid) { }` work, you must set param type to string eg. `@Get('/:uuid/stuff') public getSomething(@Param('uuid') uuid: string) { }`.

**Comment by pleerock** [comment]
resolution is to specify a correct parameter type
